/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.iss2021_resumablebw;

import it.unibo.consolegui.ConsoleGui;
import it.unibo.supports.RobotApplicationStarter;
import it.unibo.wenv.RobotInputController;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    private Object appl;
    private String result = "", result1 = "";

    @Before
    public void setUp(){
        System.out.println("AppTest | Test plan set up");
        //Set up
        System.out.println("ClientBoundaryWebsockBasicAsynch | main start n_Threads=" + Thread.activeCount());
        appl = RobotApplicationStarter.createInstance(App.class);
        result = "|1, 1, 1, 1, 1, \n|1, 0, 0, 0, 1, \n|1, 0, 0, 0, 1, \n|1, 1, 1, 1, 1, \n";
        result1 = "|r, 1, 1, 1, 1, \n|1, 0, 0, 0, 1, \n|1, 0, 0, 0, 1, \n|1, 1, 1, 1, 1, \n";
    }

    @Test public void testPlan() {
        String trip = ((App) appl).doBoundary();
        System.out.println("----------TRIP----------");
        System.out.println(trip);
        System.out.println("------------------------");
        assertTrue(trip.equals(result) || trip.equals(result1));
    }
}
